plugins {
    id 'fabric-loom' version '1.8.11'
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

repositories {
    maven { url "https://maven.nucleoid.xyz/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    // This specific format tells Loom to use Intermediary for both the
    // obfuscation layer AND the readable layer.
    mappings loom.layered() {
        officialMojangMappings()
        // This removes the need for a 'named' layer that doesn't exist yet
    }

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "eu.pb4:placeholder-api:${project.papi_version}"
    modImplementation "eu.pb4:polymer-resource-pack:${project.polymer_version}"
    modImplementation "eu.pb4:polymer-autohost:${project.polymer_version}"

    include "eu.pb4:placeholder-api:${project.papi_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = "UTF-8"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}